version: '3.4'
services:
  postgres:
    container_name: dtk-database
    image: postgres
    env_file:
      - ./.env
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5442:5442'
    networks:
      - dtk
    restart: on-failure
    

networks:
  dtk:
volumes:
  postgres:
